baseURL = "https://naniz.co"
title = "Nani Ravikumar"

DefaultContentLanguage = "en"

theme="hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"


buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = false

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Narayana Ravikumar"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "Where the magic happens"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Homepage and blog by Narayana Ravikumar"
  keywords = "homepage, blog, economics, finance, development, programming, journal"
  images = [""]

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

    # Social icons
  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/ninja_in_pyjama_217/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/narayanaravikumar/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/naniroot"

  [[params.social]]
    name = "github"
    url  = "https://github.com/naniroot"

  [[params.social]]
    name = "facebook"
    url  = "https://www.facebook.com/nanikumar17"

[languages]
  [languages.en]
    title = 'Nani Ravikumar'
    subtitle = "Where the magic happens"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "/home/Naniz"
      logoHomeLink = "/"
      logoCursorDisabled = true
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"  
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"